import { createContext, useState, useContext, useEffect } from 'react';

export const translations = {
  ru: {
    // AI
    ai_match: "Выбор ИИ",
    why_love_it: "Почему вам это понравится:",
    // Profile
    profile_title: "Личный Кабинет",
    logout: "Выйти из аккаунта",
    favorite_genres: "Любимые жанры:",
    library: "Медиатека",
    in_watchlist: "В Watchlist",
    ratings_left: "Оценок оставлено",
    tab_watchlist: "Мой Watchlist",
    tab_ratings: "Мои Оценки",
    tab_settings: "Настройки",
    empty_watchlist: "Вы еще ничего не сохранили.",
    empty_ratings: "Вам предстоит оценить что-нибудь грандиозное!",
    find_cool_stuff: "Найти что-нибудь классное",
    account_settings: "Настройки Аккаунта",
    light_theme: "Светлая тема",
    light_theme_desc: "Включить светлое оформление интерфейса",
    notifications: "Уведомления",
    notifications_desc: "Получать письма с новыми рекомендациями",
    public_profile: "Публичный профиль",
    public_profile_desc: "Показывать мои оценки другим пользователям",
    danger_zone: "Опасная зона",
    delete_account: "Удалить аккаунт",
    delete_account_desc: "Навсегда удалит ваш профиль и все сохраненные данные",
    delete_btn: "Удалить",
    language: "Язык",
    language_desc: "Выберите язык интерфейса",
    loading: "Загрузка профиля...",
    // Navbar
    nav_movies: "Фильмы и Сериалы",
    nav_books: "Книги",
    nav_music: "Музыка",
    nav_recommend: "Рекомендации",
    nav_profile: "Профиль",
    nav_logout: "Выйти",
    nav_login: "Вход",
    nav_register: "Регистрация",
    // Categories (for filter tabs)
    cat_all: "Все",
    cat_movies: "Фильмы",
    cat_tv: "Сериалы",
    cat_books: "Книги",
    cat_music: "Музыка",
    // Home
    search_catalog: "Поиск по каталогу...",
    nothing_found: "Увы, ничего не найдено",
    all_genres: "Все",
    // Books page
    books_title: "Библиотека",
    books_subtitle: "Погрузитесь в захватывающие миры. Лучшие книги всех времен.",
    search_books: "Поиск книг...",
    no_books_found: "Увы, книг не найдено",
    // Music page
    music_title: "Плейлист",
    music_subtitle: "Твои любимые треки и легендарные альбомы в одном месте.",
    search_music: "Поиск музыки...",
    no_music_found: "Увы, треков не найдено",
    // Recommendations page
    rec_title: "Рекомендации",
    rec_subtitle: "Персональные предложения на основе ваших вкусов.",
    no_recs: "Пока нет рекомендаций. Оценивайте контент, чтобы получить предложения!",
    // ItemDetail page
    back_to_list: "Назад к списку",
    no_description: "Описание пока отсутствует. Мы добавим его немного позже!",
    listen_preview: "Послушать отрывок (30 сек):",
    watch_trailer: "Смотреть трейлер:",
    add_watchlist: "В Watchlist",
    remove_watchlist: "Убрать из Watchlist",
    item_not_found: "Объект не найден",
    load_error: "Не удалось загрузить информацию. Возможно, объект не найден.",
    back_to_home: "Вернуться на главную",
    user_reviews: "Отзывы пользователей",
    no_reviews: "Пока нет отзывов. Будьте первым, кто поделится своим мнением!",
    watchlist_login_alert: "Для добавления в Watchlist необходимо войти в аккаунт!",
    watchlist_error: "Не удалось обновить Watchlist.",
    // Rating
    your_rating: "Ваша оценка и отзыв:",
    review_placeholder: "Напишите свои впечатления...",
    saving: "Сохранение...",
    save_review: "Сохранить отзыв",
    review_saved: "Ваш отзыв сохранен!",
    review_error: "Ошибка при сохранении.",
    login_to_rate: "Для того чтобы оставлять отзывы, нужно войти в аккаунт!",
    // HeroSlider
    more_info: "Подробнее",
    // Login
    login_title: "С возвращением!",
    email_placeholder: "Ваш Email",
    password_placeholder: "Ваш Пароль",
    login_btn: "Войти",
    loading_btn: "Загрузка...",
    no_account: "Нет аккаунта?",
    register_link: "Зарегистрироваться",
    login_error: "Ошибка входа: ",
    // Register
    register_title: "Создать аккаунт",
    nickname_placeholder: "Ваш Никнейм",
    password_hint: "Придумайте пароль (минимум 6 символов)",
    register_btn: "Зарегистрироваться",
    has_account: "Уже есть аккаунт?",
    login_link: "Войти",
    check_email: "Проверьте вашу почту для подтверждения аккаунта!",
    // Admin
    nav_admin: "Админ",
    admin_panel: "Админ-панель",
    admin_dashboard: "Дашборд",
    admin_dashboard_desc: "Общая статистика и аналитика платформы",
    admin_users: "Пользователи",
    admin_users_desc: "Управление аккаунтами пользователей",
    admin_content: "Контент",
    admin_content_desc: "Управление фильмами, сериалами, книгами и музыкой",
    admin_reviews: "Отзывы",
    admin_reviews_desc: "Модерация отзывов и рейтингов",
    admin_access_denied: "Доступ запрещён",
    admin_access_denied_desc: "У вас нет прав администратора для доступа к этой странице.",
    admin_stat_users: "Пользователей",
    admin_stat_content: "Единиц контента",
    admin_stat_reviews: "Отзывов",
    admin_stat_avg_rating: "Средний рейтинг",
    admin_top_rated: "Топ по рейтингу",
    admin_top_watchlisted: "Топ по сохранениям",
    admin_reviews_count: "отзывов",
    admin_saves: "сохранений",
    admin_no_data: "Пока нет данных",
    admin_search_users: "Поиск по email...",
    admin_users_total: "пользователей",
    admin_col_user: "Пользователь",
    admin_col_reviews: "Отзывы",
    admin_col_status: "Статус",
    admin_col_role: "Роль",
    admin_col_registered: "Регистрация",
    admin_col_actions: "Действия",
    admin_col_title: "Название",
    admin_col_category: "Категория",
    admin_col_genre: "Жанр",
    admin_col_content: "Контент",
    admin_col_rating: "Рейтинг",
    admin_col_review: "Отзыв",
    admin_col_date: "Дата",
    admin_banned: "Заблокирован",
    admin_active: "Активен",
    admin_role_admin: "Админ",
    admin_ban: "Бан",
    admin_unban: "Разбан",
    admin_make_admin: "Сделать админом",
    admin_remove_admin: "Снять админа",
    admin_no_users: "Пользователи не найдены",
    admin_confirm_title: "Подтверждение",
    admin_confirm_ban: "Заблокировать пользователя?",
    admin_confirm_unban: "Разблокировать пользователя?",
    admin_confirm_make_admin: "Назначить администратором?",
    admin_confirm_remove_admin: "Снять роль администратора?",
    admin_confirm_delete_user: "Удалить пользователя и все его данные?",
    admin_confirm_delete_item: "Удалить этот контент?",
    admin_confirm_delete_review: "Удалить этот отзыв?",
    admin_cancel: "Отмена",
    admin_confirm: "Подтвердить",
    admin_search_content: "Поиск контента...",
    admin_add_item: "Добавить",
    admin_edit: "Редактировать",
    admin_edit_item: "Редактировать контент",
    admin_edit_item_desc: "Измените данные элемента каталога",
    admin_add_item_desc: "Добавить новый элемент в каталог",
    admin_no_content: "Контент не найден",
    admin_fill_required: "Заполните обязательные поля",
    admin_save_error: "Ошибка сохранения",
    admin_delete_error: "Ошибка удаления",
    admin_save: "Сохранить",
    admin_desc_ru: "Описание (RU)",
    admin_desc_en: "Описание (EN)",
    admin_desc_kz: "Описание (KZ)",
    admin_image_url: "URL постера",
    admin_trailer_url: "URL трейлера (YouTube embed)",
    admin_preview_url: "URL аудио-превью",
    admin_artist: "Исполнитель",
    admin_search_reviews: "Поиск по отзывам...",
    admin_reviews_total: "отзывов",
    admin_no_reviews: "Отзывы не найдены"
  },
  en: {
    // AI
    ai_match: "AI Match",
    why_love_it: "Why you'll love it:",
    // Profile
    profile_title: "My Account",
    logout: "Sign Out",
    favorite_genres: "Favorite Genres:",
    library: "My Media",
    in_watchlist: "In Watchlist",
    ratings_left: "Ratings Given",
    tab_watchlist: "My Watchlist",
    tab_ratings: "My Ratings",
    tab_settings: "Settings",
    empty_watchlist: "You haven't saved anything yet.",
    empty_ratings: "You still have great things to rate!",
    find_cool_stuff: "Find something cool",
    account_settings: "Account Settings",
    light_theme: "Light Theme",
    light_theme_desc: "Enable light interface mode",
    notifications: "Notifications",
    notifications_desc: "Receive emails with new recommendations",
    public_profile: "Public Profile",
    public_profile_desc: "Show my ratings to other users",
    danger_zone: "Danger Zone",
    delete_account: "Delete Account",
    delete_account_desc: "Permanently delete your profile and all saved data",
    delete_btn: "Delete",
    language: "Language",
    language_desc: "Select interface language",
    loading: "Loading profile...",
    // Navbar
    nav_movies: "Movies & TV",
    nav_books: "Books",
    nav_music: "Music",
    nav_recommend: "Recommendations",
    nav_profile: "Profile",
    nav_logout: "Logout",
    nav_login: "Sign In",
    nav_register: "Sign Up",
    // Categories
    cat_all: "All",
    cat_movies: "Movies",
    cat_tv: "TV Series",
    cat_books: "Books",
    cat_music: "Music",
    // Home
    search_catalog: "Search catalog...",
    nothing_found: "Sorry, nothing found",
    all_genres: "All",
    // Books page
    books_title: "Library",
    books_subtitle: "Dive into captivating worlds. The best books of all time.",
    search_books: "Search books...",
    no_books_found: "Sorry, no books found",
    // Music page
    music_title: "Playlist",
    music_subtitle: "Your favorite tracks and legendary albums in one place.",
    search_music: "Search music...",
    no_music_found: "Sorry, no tracks found",
    // Recommendations page
    rec_title: "Recommendations",
    rec_subtitle: "Personal suggestions based on your taste.",
    no_recs: "No recommendations yet. Rate content to get suggestions!",
    // ItemDetail page
    back_to_list: "Back to list",
    no_description: "No description available yet. We'll add it soon!",
    listen_preview: "Listen to a preview (30 sec):",
    watch_trailer: "Watch trailer:",
    add_watchlist: "Add to Watchlist",
    remove_watchlist: "Remove from Watchlist",
    item_not_found: "Item not found",
    load_error: "Failed to load information. The item may not exist.",
    back_to_home: "Back to home",
    user_reviews: "User Reviews",
    no_reviews: "No reviews yet. Be the first to share your thoughts!",
    watchlist_login_alert: "Please sign in to add items to your Watchlist!",
    watchlist_error: "Failed to update Watchlist.",
    // Rating
    your_rating: "Your rating and review:",
    review_placeholder: "Share your thoughts...",
    saving: "Saving...",
    save_review: "Save Review",
    review_saved: "Your review has been saved!",
    review_error: "Error saving review.",
    login_to_rate: "Please sign in to leave reviews!",
    // HeroSlider
    more_info: "Learn More",
    // Login
    login_title: "Welcome Back!",
    email_placeholder: "Your Email",
    password_placeholder: "Your Password",
    login_btn: "Sign In",
    loading_btn: "Loading...",
    no_account: "Don't have an account?",
    register_link: "Sign Up",
    login_error: "Login error: ",
    // Register
    register_title: "Create Account",
    nickname_placeholder: "Your Nickname",
    password_hint: "Create a password (min. 6 characters)",
    register_btn: "Sign Up",
    has_account: "Already have an account?",
    login_link: "Sign In",
    check_email: "Check your email to confirm your account!",
    // Admin
    nav_admin: "Admin",
    admin_panel: "Admin Panel",
    admin_dashboard: "Dashboard",
    admin_dashboard_desc: "Platform overview and analytics",
    admin_users: "Users",
    admin_users_desc: "Manage user accounts",
    admin_content: "Content",
    admin_content_desc: "Manage movies, series, books and music",
    admin_reviews: "Reviews",
    admin_reviews_desc: "Moderate reviews and ratings",
    admin_access_denied: "Access Denied",
    admin_access_denied_desc: "You don't have admin privileges to access this page.",
    admin_stat_users: "Users",
    admin_stat_content: "Content Items",
    admin_stat_reviews: "Reviews",
    admin_stat_avg_rating: "Avg. Rating",
    admin_top_rated: "Top Rated",
    admin_top_watchlisted: "Most Saved",
    admin_reviews_count: "reviews",
    admin_saves: "saves",
    admin_no_data: "No data yet",
    admin_search_users: "Search by email...",
    admin_users_total: "users",
    admin_col_user: "User",
    admin_col_reviews: "Reviews",
    admin_col_status: "Status",
    admin_col_role: "Role",
    admin_col_registered: "Registered",
    admin_col_actions: "Actions",
    admin_col_title: "Title",
    admin_col_category: "Category",
    admin_col_genre: "Genre",
    admin_col_content: "Content",
    admin_col_rating: "Rating",
    admin_col_review: "Review",
    admin_col_date: "Date",
    admin_banned: "Banned",
    admin_active: "Active",
    admin_role_admin: "Admin",
    admin_ban: "Ban",
    admin_unban: "Unban",
    admin_make_admin: "Make Admin",
    admin_remove_admin: "Remove Admin",
    admin_no_users: "No users found",
    admin_confirm_title: "Confirmation",
    admin_confirm_ban: "Ban this user?",
    admin_confirm_unban: "Unban this user?",
    admin_confirm_make_admin: "Make this user an admin?",
    admin_confirm_remove_admin: "Remove admin role?",
    admin_confirm_delete_user: "Delete user and all their data?",
    admin_confirm_delete_item: "Delete this content?",
    admin_confirm_delete_review: "Delete this review?",
    admin_cancel: "Cancel",
    admin_confirm: "Confirm",
    admin_search_content: "Search content...",
    admin_add_item: "Add",
    admin_edit: "Edit",
    admin_edit_item: "Edit Content",
    admin_edit_item_desc: "Update catalog item details",
    admin_add_item_desc: "Add a new item to the catalog",
    admin_no_content: "No content found",
    admin_fill_required: "Fill in required fields",
    admin_save_error: "Save error",
    admin_delete_error: "Delete error",
    admin_save: "Save",
    admin_desc_ru: "Description (RU)",
    admin_desc_en: "Description (EN)",
    admin_desc_kz: "Description (KZ)",
    admin_image_url: "Poster URL",
    admin_trailer_url: "Trailer URL (YouTube embed)",
    admin_preview_url: "Audio preview URL",
    admin_artist: "Artist",
    admin_search_reviews: "Search reviews...",
    admin_reviews_total: "reviews",
    admin_no_reviews: "No reviews found"
  },
  kz: {
    // AI
    ai_match: "AI Таңдауы",
    why_love_it: "Неге бұл сізге ұнайды:",
    // Profile
    profile_title: "Жеке Кабинет",
    logout: "Аккаунттан шығу",
    favorite_genres: "Сүйікті жанрлар:",
    library: "Медиатека",
    in_watchlist: "Watchlist-те",
    ratings_left: "Берілген бағалар",
    tab_watchlist: "Менің Watchlist-ім",
    tab_ratings: "Менің Бағаларым",
    tab_settings: "Баптаулар",
    empty_watchlist: "Сіз әлі ештеңе сақтамадыңыз.",
    empty_ratings: "Алдыңызда бағалайтын тамаша дүниелер күтіп тұр!",
    find_cool_stuff: "Керемет бірдеңе табу",
    account_settings: "Аккаунт Баптаулары",
    light_theme: "Жарық тақырып",
    light_theme_desc: "Интерфейстің жарық безендіруін қосу",
    notifications: "Хабарландырулар",
    notifications_desc: "Жаңа ұсыныстары бар хаттар алу",
    public_profile: "Ашық профиль",
    public_profile_desc: "Менің бағаларымды басқа пайдаланушыларға көрсету",
    danger_zone: "Қауіпті аймақ",
    delete_account: "Аккаунтты өшіру",
    delete_account_desc: "Профильді және барлық сақталған деректерді біржолата өшіру",
    delete_btn: "Өшіру",
    language: "Тіл",
    language_desc: "Интерфейс тілін таңдаңыз",
    loading: "Профиль жүктелуде...",
    // Navbar
    nav_movies: "Фильмдер мен Сериалдар",
    nav_books: "Кітаптар",
    nav_music: "Музыка",
    nav_recommend: "Ұсыныстар",
    nav_profile: "Профиль",
    nav_logout: "Шығу",
    nav_login: "Кіру",
    nav_register: "Тіркелу",
    // Categories
    cat_all: "Барлығы",
    cat_movies: "Фильмдер",
    cat_tv: "Сериалдар",
    cat_books: "Кітаптар",
    cat_music: "Музыка",
    // Home
    search_catalog: "Каталогтан іздеу...",
    nothing_found: "Кешіріңіз, ештеңе табылмады",
    all_genres: "Барлығы",
    // Books page
    books_title: "Кітапхана",
    books_subtitle: "Тартымды әлемдерге еніңіз. Барлық уақыттағы ең жақсы кітаптар.",
    search_books: "Кітаптарды іздеу...",
    no_books_found: "Кешіріңіз, кітаптар табылмады",
    // Music page
    music_title: "Плейлист",
    music_subtitle: "Сүйікті тректеріңіз бен аңыз альбомдар бір жерде.",
    search_music: "Музыка іздеу...",
    no_music_found: "Кешіріңіз, тректер табылмады",
    // Recommendations page
    rec_title: "Ұсыныстар",
    rec_subtitle: "Сіздің талғамыңызға негізделген жеке ұсыныстар.",
    no_recs: "Әзірге ұсыныстар жоқ. Ұсыныстар алу үшін мазмұнды бағалаңыз!",
    // ItemDetail page
    back_to_list: "Тізімге оралу",
    no_description: "Сипаттама әзірге жоқ. Біз оны жақында қосамыз!",
    listen_preview: "Үзіндіні тыңдау (30 сек):",
    watch_trailer: "Трейлерді көру:",
    add_watchlist: "Watchlist-ке қосу",
    remove_watchlist: "Watchlist-тен алып тастау",
    item_not_found: "Объект табылмады",
    load_error: "Ақпаратты жүктеу мүмкін болмады. Объект табылмаған болуы мүмкін.",
    back_to_home: "Басты бетке оралу",
    user_reviews: "Пайдаланушылар пікірлері",
    no_reviews: "Әзірге пікір жоқ. Пікіріңізді бөлісіңіз!",
    watchlist_login_alert: "Watchlist-ке қосу үшін аккаунтқа кіруіңіз керек!",
    watchlist_error: "Watchlist-ті жаңарту мүмкін болмады.",
    // Rating
    your_rating: "Сіздің бағаңыз және пікіріңіз:",
    review_placeholder: "Әсерлеріңізді жазыңыз...",
    saving: "Сақтау...",
    save_review: "Пікірді сақтау",
    review_saved: "Пікіріңіз сақталды!",
    review_error: "Сақтау кезінде қате.",
    login_to_rate: "Пікір қалдыру үшін аккаунтқа кіруіңіз керек!",
    // HeroSlider
    more_info: "Толығырақ",
    // Login
    login_title: "Қайта келуіңізбен!",
    email_placeholder: "Сіздің Email",
    password_placeholder: "Сіздің Құпия сөз",
    login_btn: "Кіру",
    loading_btn: "Жүктелуде...",
    no_account: "Аккаунтыңыз жоқ па?",
    register_link: "Тіркелу",
    login_error: "Кіру қатесі: ",
    // Register
    register_title: "Аккаунт жасау",
    nickname_placeholder: "Сіздің Лақап атыңыз",
    password_hint: "Құпия сөз ойлап табыңыз (кемінде 6 таңба)",
    register_btn: "Тіркелу",
    has_account: "Аккаунтыңыз бар ма?",
    login_link: "Кіру",
    check_email: "Аккаунтты растау үшін поштаңызды тексеріңіз!",
    // Admin
    nav_admin: "Админ",
    admin_panel: "Админ-панель",
    admin_dashboard: "Дашборд",
    admin_dashboard_desc: "Платформаның жалпы статистикасы",
    admin_users: "Пайдаланушылар",
    admin_users_desc: "Пайдаланушы аккаунттарын басқару",
    admin_content: "Контент",
    admin_content_desc: "Фильмдерді, сериалдарды, кітаптарды және музыканы басқару",
    admin_reviews: "Пікірлер",
    admin_reviews_desc: "Пікірлер мен рейтингтерді модерациялау",
    admin_access_denied: "Кіруге тыйым салынған",
    admin_access_denied_desc: "Сізде бұл бетке кіру үшін әкімші құқықтары жоқ.",
    admin_stat_users: "Пайдаланушылар",
    admin_stat_content: "Контент бірліктері",
    admin_stat_reviews: "Пікірлер",
    admin_stat_avg_rating: "Орташа рейтинг",
    admin_top_rated: "Рейтинг бойынша үздік",
    admin_top_watchlisted: "Сақтаулар бойынша үздік",
    admin_reviews_count: "пікір",
    admin_saves: "сақтау",
    admin_no_data: "Деректер жоқ",
    admin_search_users: "Email бойынша іздеу...",
    admin_users_total: "пайдаланушы",
    admin_col_user: "Пайдаланушы",
    admin_col_reviews: "Пікірлер",
    admin_col_status: "Күй",
    admin_col_role: "Рөл",
    admin_col_registered: "Тіркелу",
    admin_col_actions: "Әрекеттер",
    admin_col_title: "Атауы",
    admin_col_category: "Санат",
    admin_col_genre: "Жанр",
    admin_col_content: "Контент",
    admin_col_rating: "Рейтинг",
    admin_col_review: "Пікір",
    admin_col_date: "Күні",
    admin_banned: "Бұғатталған",
    admin_active: "Белсенді",
    admin_role_admin: "Әкімші",
    admin_ban: "Бұғаттау",
    admin_unban: "Бұғаттан шығару",
    admin_make_admin: "Әкімші ету",
    admin_remove_admin: "Әкімшіні алып тастау",
    admin_no_users: "Пайдаланушылар табылмады",
    admin_confirm_title: "Растау",
    admin_confirm_ban: "Пайдаланушыны бұғаттау керек пе?",
    admin_confirm_unban: "Бұғаттан шығару керек пе?",
    admin_confirm_make_admin: "Әкімші ету керек пе?",
    admin_confirm_remove_admin: "Әкімші рөлін алып тастау керек пе?",
    admin_confirm_delete_user: "Пайдаланушыны жою керек пе?",
    admin_confirm_delete_item: "Бұл контентті жою керек пе?",
    admin_confirm_delete_review: "Бұл пікірді жою керек пе?",
    admin_cancel: "Бас тарту",
    admin_confirm: "Растау",
    admin_search_content: "Контентті іздеу...",
    admin_add_item: "Қосу",
    admin_edit: "Өзгерту",
    admin_edit_item: "Контентті өзгерту",
    admin_edit_item_desc: "Каталог элементін жаңарту",
    admin_add_item_desc: "Каталогқа жаңа элемент қосу",
    admin_no_content: "Контент табылмады",
    admin_fill_required: "Міндетті өрістерді толтырыңыз",
    admin_save_error: "Сақтау қатесі",
    admin_delete_error: "Жою қатесі",
    admin_save: "Сақтау",
    admin_desc_ru: "Сипаттама (RU)",
    admin_desc_en: "Сипаттама (EN)",
    admin_desc_kz: "Сипаттама (KZ)",
    admin_image_url: "Постер URL",
    admin_trailer_url: "Трейлер URL",
    admin_preview_url: "Аудио URL",
    admin_artist: "Орындаушы",
    admin_search_reviews: "Пікірлерді іздеу...",
    admin_reviews_total: "пікір",
    admin_no_reviews: "Пікірлер табылмады"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('app-lang') || 'ru');

  useEffect(() => {
    localStorage.setItem('app-lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['ru']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
