import { createContext, useState, useContext, useEffect } from 'react';

export const translations = {
  ru: {
    // AI
    ai_match: "Выбор ИИ",
    why_love_it: "Почему вам это понравится:",
    // Profile
    profile_title: "Личный Кабинет",
    logout: "Выйти из аккаунта",
    favorite_genres: "Любимые жанры:",
    library: "Медиатека",
    in_watchlist: "В списке",
    ratings_left: "Оценок оставлено",
    tab_watchlist: "Мой список",
    tab_my_ratings: "Мои оценки",
    tab_settings: "Настройки",
    empty_watchlist: "Вы еще ничего не сохранили.",
    empty_ratings: "Вам предстоит оценить что-нибудь грандиозное!",
    find_cool_stuff: "Найти что-нибудь классное",
    account_settings: "Настройки Аккаунта",
    light_theme: "Светлая тема",
    light_theme_desc: "Включить светлое оформление интерфейса",
    notifications: "Уведомления",
    notifications_desc: "Получать письма с новыми рекомендациями",
    public_profile: "Публичный профиль",
    public_profile_desc: "Показывать мои оценки другим пользователям",
    danger_zone: "Опасная зона",
    delete_account: "Удалить аккаунт",
    delete_account_desc: "Навсегда удалит ваш профиль и все сохраненные данные",
    delete_btn: "Удалить",
    language: "Язык",
    language_desc: "Выберите язык интерфейса",
    loading: "Загрузка профиля...",
    // Navbar
    nav_movies: "Фильмы и Сериалы",
    nav_books: "Книги",
    nav_music: "Музыка",
    nav_recommend: "Рекомендации",
    nav_profile: "Профиль",
    nav_logout: "Выйти",
    nav_login: "Вход",
    nav_register: "Регистрация",
    // Categories (for filter tabs)
    cat_all: "Все",
    cat_movies: "Фильмы",
    cat_tv: "Сериалы",
    cat_books: "Книги",
    cat_music: "Музыка",
    // Home
    search_catalog: "Поиск по названию, жанру...",
    nothing_found: "Увы, ничего не найдено",
    all_genres: "Все",
    // Books page
    books_title: "Библиотека",
    books_subtitle: "Погрузитесь в захватывающие миры. Лучшие книги всех времен.",
    search_books: "Поиск по названию, жанру...",
    no_books_found: "Увы, книг не найдено",
    // Music page
    music_title: "Плейлист",
    music_subtitle: "Твои любимые треки и легендарные альбомы в одном месте.",
    search_music: "Поиск по названию, жанру, исполнителю...",
    no_music_found: "Увы, треков не найдено",
    // Recommendations page
    rec_title: "Рекомендации",
    rec_subtitle: "Персональные предложения на основе ваших вкусов.",
    no_recs: "Пока нет рекомендаций. Оценивайте контент, чтобы получить предложения!",
    rec_ai_analyzing: "ИИ анализирует ваши предпочтения...",
    rec_ai_fallback: "ИИ временно недоступен — показаны рекомендации по вашим жанрам.",
    // ItemDetail page
    back_to_list: "Назад к списку",
    no_description: "Описание пока отсутствует. Мы добавим его немного позже!",
    listen_preview: "Послушать отрывок (30 сек):",
    watch_trailer: "Смотреть трейлер:",
    add_watchlist: "В список",
    remove_watchlist: "Убрать из списка",
    item_not_found: "Объект не найден",
    load_error: "Не удалось загрузить информацию. Возможно, объект не найден.",
    back_to_home: "Вернуться на главную",
    user_reviews: "Отзывы пользователей",
    no_reviews: "Пока нет отзывов. Будьте первым, кто поделится своим мнением!",
    reply: "Ответить",
    write_reply: "Напишите ответ...",
    send: "Отправить",
    replies_count: "ответов",
    show_replies: "Ответы",
    hide_replies: "Скрыть",
    delete: "Удалить",
    confirm_delete_review: "Вы уверены, что хотите удалить этот отзыв?",
    watchlist_login_alert: "Для добавления в список необходимо войти в аккаунт!",
    watchlist_error: "Не удалось обновить список.",
    // Rating
    your_rating: "Ваша оценка и отзыв:",
    review_placeholder: "Напишите свои впечатления...",
    saving: "Сохранение...",
    save_review: "Сохранить отзыв",
    review_saved: "Ваш отзыв сохранен!",
    review_error: "Ошибка при сохранении.",
    login_to_rate: "Для того чтобы оставлять отзывы, нужно войти в аккаунт!",
    // HeroSlider
    more_info: "Подробнее",
    // Login
    login_title: "С возвращением!",
    email_placeholder: "Ваш Email",
    password_placeholder: "Ваш Пароль",
    login_btn: "Войти",
    loading_btn: "Загрузка...",
    no_account: "Нет аккаунта?",
    register_link: "Зарегистрироваться",
    login_error: "Ошибка входа: ",
    forgot_password: "Забыли пароль?",
    // Forgot Password page
    forgot_title: "Восстановление пароля",
    forgot_subtitle: "Введите email — мы отправим ссылку для сброса пароля.",
    forgot_btn: "Отправить ссылку",
    forgot_sent: "Письмо отправлено!",
    forgot_sent_desc: "Проверьте вашу почту и перейдите по ссылке для сброса пароля.",
    forgot_error: "Ошибка: ",
    back_to_login: "Вернуться к входу",
    // Reset Password page
    reset_title: "Новый пароль",
    reset_subtitle: "Придумайте надёжный новый пароль.",
    reset_new_password: "Новый пароль",
    reset_confirm_password: "Подтвердите пароль",
    reset_btn: "Сохранить пароль",
    reset_success: "Пароль успешно изменён!",
    reset_redirect: "Перенаправляем на страницу входа...",
    reset_password_short: "Пароль должен быть не менее 6 символов.",
    reset_password_mismatch: "Пароли не совпадают.",
    reset_error: "Ошибка: ",
    reset_verifying: "Проверяем ссылку...",
    // Register
    register_title: "Создать аккаунт",
    nickname_placeholder: "Ваш Никнейм",
    password_hint: "Придумайте пароль (минимум 8 символов)",
    pwd_min_8: "Пароль должен быть не менее 8 символов.",
    pwd_latin_only: "Пароль может содержать только английские буквы, цифры и спецсимволы.",
    pwd_very_weak: "Очень слабый",
    pwd_weak: "Слабый",
    pwd_fair: "Средний",
    pwd_strong: "Надёжный",
    pwd_very_strong: "Очень надёжный",
    register_btn: "Зарегистрироваться",
    has_account: "Уже есть аккаунт?",
    login_link: "Войти",
    check_email: "Проверьте вашу почту для подтверждения аккаунта!",
    // Admin
    nav_admin: "Админ",
    admin_panel: "Админ-панель",
    admin_dashboard: "Дашборд",
    admin_dashboard_desc: "Общая статистика и аналитика платформы",
    admin_users: "Пользователи",
    admin_users_desc: "Управление аккаунтами пользователей",
    admin_content: "Контент",
    admin_content_desc: "Управление фильмами, сериалами, книгами и музыкой",
    admin_reviews: "Отзывы",
    admin_reviews_desc: "Модерация отзывов и рейтингов",
    admin_access_denied: "Доступ запрещён",
    admin_access_denied_desc: "У вас нет прав администратора для доступа к этой странице.",
    admin_stat_users: "Пользователей",
    admin_stat_content: "Единиц контента",
    admin_stat_reviews: "Отзывов",
    admin_stat_avg_rating: "Средний рейтинг",
    admin_top_rated: "Топ по рейтингу",
    admin_top_watchlisted: "Топ по сохранениям",
    admin_reviews_count: "отзывов",
    admin_saves: "сохранений",
    admin_no_data: "Пока нет данных",
    admin_search_users: "Поиск по email...",
    admin_users_total: "пользователей",
    admin_col_user: "Пользователь",
    admin_col_reviews: "Отзывы",
    admin_col_status: "Статус",
    admin_col_role: "Роль",
    admin_col_registered: "Регистрация",
    admin_col_actions: "Действия",
    admin_col_title: "Название",
    admin_col_category: "Категория",
    admin_col_genre: "Жанр",
    admin_col_content: "Контент",
    admin_col_rating: "Рейтинг",
    admin_col_review: "Отзыв",
    admin_col_date: "Дата",
    admin_banned: "Заблокирован",
    admin_active: "Активен",
    admin_role_admin: "Админ",
    admin_ban: "Бан",
    admin_unban: "Разбан",
    admin_make_admin: "Сделать админом",
    admin_remove_admin: "Снять админа",
    admin_make_manager: "Сделать менеджером",
    admin_remove_manager: "Снять менеджера",
    admin_role_manager: "Менеджер",
    admin_confirm_make_manager: "Назначить менеджером?",
    admin_confirm_remove_manager: "Снять роль менеджера?",
    manager_panel: "Менеджер-панель",
    nav_manager: "Менеджер",
    admin_no_users: "Пользователи не найдены",
    admin_confirm_title: "Подтверждение",
    admin_confirm_ban: "Заблокировать пользователя?",
    admin_confirm_unban: "Разблокировать пользователя?",
    admin_confirm_make_admin: "Назначить администратором?",
    admin_confirm_remove_admin: "Снять роль администратора?",
    admin_confirm_delete_user: "Удалить пользователя и все его данные?",
    admin_confirm_delete_item: "Удалить этот контент?",
    admin_confirm_delete_review: "Удалить этот отзыв?",
    admin_cancel: "Отмена",
    admin_confirm: "Подтвердить",
    admin_search_content: "Поиск контента...",
    admin_add_item: "Добавить",
    admin_edit: "Редактировать",
    admin_edit_item: "Редактировать контент",
    admin_edit_item_desc: "Измените данные элемента каталога",
    admin_add_item_desc: "Добавить новый элемент в каталог",
    admin_no_content: "Контент не найден",
    admin_fill_required: "Заполните обязательные поля",
    admin_save_error: "Ошибка сохранения",
    admin_delete_error: "Ошибка удаления",
    admin_save: "Сохранить",
    admin_desc_ru: "Описание (RU)",
    admin_desc_en: "Описание (EN)",
    admin_desc_kz: "Описание (KZ)",
    admin_image_url: "URL постера",
    admin_trailer_url: "URL трейлера (YouTube embed)",
    admin_preview_url: "URL аудио-превью",
    admin_artist: "Исполнитель",
    admin_search_reviews: "Поиск по отзывам...",
    admin_reviews_total: "отзывов",
    admin_no_reviews: "Отзывы не найдены",
    viewing_now: "смотрят сейчас",
    director: "Режиссер",
    cast: "В ролях",
    // Filter & Profile extras
    filter_btn: "Фильтр",
    adv_filter_title: "Расширенный фильтр",
    adv_sort_by: "Сортировка",
    adv_category: "Категория",
    adv_genres: "Жанры",
    adv_selected: "выбрано",
    adv_found: "Найдено",
    adv_apply: "Применить",
    adv_filter_reset: "Сбросить",
    sort_default: "По умолчанию",
    sort_title_asc: "Название А→Я",
    sort_title_desc: "Название Я→А",
    sort_rating_desc: "Рейтинг ↓",
    sort_rating_asc: "Рейтинг ↑",
    sort_year_desc: "Новые",
    sort_year_asc: "Старые",
    tab_feed: "Лента активности",
    folder_all: "Все",
    folder_unsorted: "Без папки",
    folder_planned: "В планах",
    folder_watching: "Смотрю",
    folder_watched: "Просмотрено",
    folder_dropped: "Брошено",
    folder_assign: "В папку...",
    remove_folder: "Убрать из папки",
    about_me: "О себе",
    about_me_desc: "Расскажите немного о себе, своих интересах и любимых жанрах",
    about_me_placeholder: "Всем привет! Люблю научную фантастику и инди-музыку...",
    nickname_label: "Никнейм",
    nickname_desc: "Ваше отображаемое имя на платформе",
    nickname_ph: "Ваш никнейм",
    saves_auto: "Сохраняется автоматически",
    avatar_style: "Стиль Аватарки (DiceBear)",
    share_profile: "Поделиться профилем",
    copy_link: "Скопировать ссылку на мою страницу",
    link_copied: "Ссылка скопирована!",
    copy_manual: "Скопируйте ссылку вручную: ",
    followers_label: "подписчиков",
    following_label: "подписок",
    followers_title: "Подписчики",
    following_title: "Подписки",
    empty_list: "Список пуст",
    profile_hidden: "Профиль скрыт",
    confirm_delete_account: "Вы уверены, что хотите НАВСЕГДА удалить свой аккаунт? Это действие нельзя отменить.",
    folder_empty: "В папке пока пусто.",
    error_save_settings: "Ошибка при сохранении настроек.",
    avatar_updated: "Аватарка успешно обновлена!",
    avatar_upload_error: "Ошибка загрузки. Убедитесь, что вы создали публичный бакет 'avatars' в Supabase Storage.",
    avatar_style_error: "Ошибка при выборе стиля.",
    error_delete_account: "Ошибка: ",
    // Footer
    footer_explore: "Изучить",
    footer_account: "Аккаунт",
    footer_rights: "Все права защищены.",
    // Notifications
    notifications_title: "Уведомления",
    no_notifications: "У вас пока нет уведомлений.",
    user_unknown: "Пользователь",
    notif_like: " оценил(а) ваш отзыв! ❤️",
    notif_follow: " подписался(ась) на вас!",
    // Dashboard new strings
    dash_content_by_cat: "Контент по категориям",
    dash_cat_filter: "Фильтр по категории",
    dash_stats_for: "Статистика:",
    dash_records: "записей",
    dash_rating_dist: "Распределение оценок",
    dash_items_count: "шт.",
    dash_cat_movies: "🎬 Фильмы",
    dash_cat_tv: "📺 Сериалы",
    dash_cat_books: "📚 Книги",
    dash_cat_music: "🎵 Музыка"
  },
  en: {
    // AI
    ai_match: "AI Match",
    why_love_it: "Why you'll love it:",
    // Profile
    profile_title: "My Account",
    logout: "Sign Out",
    favorite_genres: "Favorite Genres:",
    library: "My Media",
    in_watchlist: "In Watchlist",
    ratings_left: "Ratings Given",
    tab_watchlist: "Watchlist",
    tab_my_ratings: "My Ratings",
    tab_settings: "Settings",
    empty_watchlist: "You haven't saved anything yet.",
    empty_ratings: "You still have great things to rate!",
    find_cool_stuff: "Find something cool",
    account_settings: "Account Settings",
    light_theme: "Light Theme",
    light_theme_desc: "Enable light interface mode",
    notifications: "Notifications",
    notifications_desc: "Receive emails with new recommendations",
    public_profile: "Public Profile",
    public_profile_desc: "Show my ratings to other users",
    danger_zone: "Danger Zone",
    delete_account: "Delete Account",
    delete_account_desc: "Permanently delete your profile and all saved data",
    delete_btn: "Delete",
    language: "Language",
    language_desc: "Select interface language",
    loading: "Loading profile...",
    // Navbar
    nav_movies: "Movies & TV",
    nav_books: "Books",
    nav_music: "Music",
    nav_recommend: "Recommendations",
    nav_profile: "Profile",
    nav_logout: "Logout",
    nav_login: "Sign In",
    nav_register: "Sign Up",
    // Categories
    cat_all: "All",
    cat_movies: "Movies",
    cat_tv: "TV Series",
    cat_books: "Books",
    cat_music: "Music",
    // Home
    search_catalog: "Search by title, genre...",
    nothing_found: "Sorry, nothing found",
    all_genres: "All",
    // Books page
    books_title: "Library",
    books_subtitle: "Dive into captivating worlds. The best books of all time.",
    search_books: "Search by title, genre...",
    no_books_found: "Sorry, no books found",
    // Music page
    music_title: "Playlist",
    music_subtitle: "Your favorite tracks and legendary albums in one place.",
    search_music: "Search by title, genre, artist...",
    no_music_found: "Sorry, no tracks found",
    // Recommendations page
    rec_title: "Recommendations",
    rec_subtitle: "Personal suggestions based on your taste.",
    no_recs: "No recommendations yet. Rate content to get suggestions!",
    rec_ai_analyzing: "AI is analyzing your taste...",
    rec_ai_fallback: "AI is temporarily unavailable — showing genre-based picks.",
    // ItemDetail page
    back_to_list: "Back to list",
    no_description: "No description available yet. We'll add it soon!",
    listen_preview: "Listen to a preview (30 sec):",
    watch_trailer: "Watch trailer:",
    add_watchlist: "Add to Watchlist",
    remove_watchlist: "Remove from Watchlist",
    item_not_found: "Item not found",
    load_error: "Failed to load information. The item may not exist.",
    back_to_home: "Back to home",
    user_reviews: "User Reviews",
    no_reviews: "No reviews yet. Be the first to share your thoughts!",
    reply: "Reply",
    write_reply: "Write a reply...",
    send: "Send",
    replies_count: "replies",
    show_replies: "Replies",
    hide_replies: "Hide",
    delete: "Delete",
    confirm_delete_review: "Are you sure you want to delete this review?",
    watchlist_login_alert: "Please sign in to add items to your Watchlist!",
    watchlist_error: "Failed to update Watchlist.",
    // Rating
    your_rating: "Your rating and review:",
    review_placeholder: "Share your thoughts...",
    saving: "Saving...",
    save_review: "Save Review",
    review_saved: "Your review has been saved!",
    review_error: "Error saving review.",
    login_to_rate: "Please sign in to leave reviews!",
    // HeroSlider
    more_info: "Learn More",
    // Login
    login_title: "Welcome Back!",
    email_placeholder: "Your Email",
    password_placeholder: "Your Password",
    login_btn: "Sign In",
    loading_btn: "Loading...",
    no_account: "Don't have an account?",
    register_link: "Sign Up",
    login_error: "Login error: ",
    forgot_password: "Forgot password?",
    // Forgot Password page
    forgot_title: "Reset Password",
    forgot_subtitle: "Enter your email and we'll send you a reset link.",
    forgot_btn: "Send Reset Link",
    forgot_sent: "Email sent!",
    forgot_sent_desc: "Check your inbox and follow the link to reset your password.",
    forgot_error: "Error: ",
    back_to_login: "Back to Sign In",
    // Reset Password page
    reset_title: "New Password",
    reset_subtitle: "Create a strong new password for your account.",
    reset_new_password: "New password",
    reset_confirm_password: "Confirm password",
    reset_btn: "Save Password",
    reset_success: "Password changed successfully!",
    reset_redirect: "Redirecting to sign in...",
    reset_password_short: "Password must be at least 6 characters.",
    reset_password_mismatch: "Passwords do not match.",
    reset_error: "Error: ",
    reset_verifying: "Verifying link...",
    // Register
    register_title: "Create Account",
    nickname_placeholder: "Your Nickname",
    password_hint: "Create a password (min. 8 characters)",
    pwd_min_8: "Password must be at least 8 characters.",
    pwd_latin_only: "Password can only contain English letters, numbers, and special characters.",
    pwd_very_weak: "Very weak",
    pwd_weak: "Weak",
    pwd_fair: "Fair",
    pwd_strong: "Strong",
    pwd_very_strong: "Very strong",
    register_btn: "Sign Up",
    has_account: "Already have an account?",
    login_link: "Sign In",
    check_email: "Check your email to confirm your account!",
    // Admin
    nav_admin: "Admin",
    admin_panel: "Admin Panel",
    admin_dashboard: "Dashboard",
    admin_dashboard_desc: "Platform overview and analytics",
    admin_users: "Users",
    admin_users_desc: "Manage user accounts",
    admin_content: "Content",
    admin_content_desc: "Manage movies, series, books and music",
    admin_reviews: "Reviews",
    admin_reviews_desc: "Moderate reviews and ratings",
    admin_access_denied: "Access Denied",
    admin_access_denied_desc: "You don't have admin privileges to access this page.",
    admin_stat_users: "Users",
    admin_stat_content: "Content Items",
    admin_stat_reviews: "Reviews",
    admin_stat_avg_rating: "Avg. Rating",
    admin_top_rated: "Top Rated",
    admin_top_watchlisted: "Most Saved",
    admin_reviews_count: "reviews",
    admin_saves: "saves",
    admin_no_data: "No data yet",
    admin_search_users: "Search by email...",
    admin_users_total: "users",
    admin_col_user: "User",
    admin_col_reviews: "Reviews",
    admin_col_status: "Status",
    admin_col_role: "Role",
    admin_col_registered: "Registered",
    admin_col_actions: "Actions",
    admin_col_title: "Title",
    admin_col_category: "Category",
    admin_col_genre: "Genre",
    admin_col_content: "Content",
    admin_col_rating: "Rating",
    admin_col_review: "Review",
    admin_col_date: "Date",
    admin_banned: "Banned",
    admin_active: "Active",
    admin_role_admin: "Admin",
    admin_ban: "Ban",
    admin_unban: "Unban",
    admin_make_admin: "Make Admin",
    admin_remove_admin: "Remove Admin",
    admin_make_manager: "Make Manager",
    admin_remove_manager: "Remove Manager",
    admin_role_manager: "Manager",
    admin_confirm_make_manager: "Make this user a manager?",
    admin_confirm_remove_manager: "Remove manager role?",
    manager_panel: "Manager Panel",
    nav_manager: "Manager",
    admin_no_users: "No users found",
    admin_confirm_title: "Confirmation",
    admin_confirm_ban: "Ban this user?",
    admin_confirm_unban: "Unban this user?",
    admin_confirm_make_admin: "Make this user an admin?",
    admin_confirm_remove_admin: "Remove admin role?",
    admin_confirm_delete_user: "Delete user and all their data?",
    admin_confirm_delete_item: "Delete this content?",
    admin_confirm_delete_review: "Delete this review?",
    admin_cancel: "Cancel",
    admin_confirm: "Confirm",
    admin_search_content: "Search content...",
    admin_add_item: "Add",
    admin_edit: "Edit",
    admin_edit_item: "Edit Content",
    admin_edit_item_desc: "Update catalog item details",
    admin_add_item_desc: "Add a new item to the catalog",
    admin_no_content: "No content found",
    admin_fill_required: "Fill in required fields",
    admin_save_error: "Save error",
    admin_delete_error: "Delete error",
    admin_save: "Save",
    admin_desc_ru: "Description (RU)",
    admin_desc_en: "Description (EN)",
    admin_desc_kz: "Description (KZ)",
    admin_image_url: "Poster URL",
    admin_trailer_url: "Trailer URL (YouTube embed)",
    admin_preview_url: "Audio preview URL",
    admin_artist: "Artist",
    admin_search_reviews: "Search reviews...",
    admin_reviews_total: "reviews",
    admin_no_reviews: "No reviews found",
    viewing_now: "viewing now",
    director: "Director",
    cast: "Cast",
    // Filter & Profile extras
    filter_btn: "Filter",
    adv_filter_title: "Advanced Filter",
    adv_sort_by: "Sort by",
    adv_category: "Category",
    adv_genres: "Genres",
    adv_selected: "selected",
    adv_found: "Found",
    adv_apply: "Apply",
    adv_filter_reset: "Reset",
    sort_default: "Default",
    sort_title_asc: "Title A→Z",
    sort_title_desc: "Title Z→A",
    sort_rating_desc: "Rating ↓",
    sort_rating_asc: "Rating ↑",
    sort_year_desc: "Newest",
    sort_year_asc: "Oldest",
    tab_feed: "Activity Feed",
    folder_all: "All",
    folder_unsorted: "Unsorted",
    folder_planned: "Planned",
    folder_watching: "Watching",
    folder_watched: "Watched",
    folder_dropped: "Dropped",
    folder_assign: "To folder...",
    remove_folder: "Remove from folder",
    about_me: "About Me",
    about_me_desc: "Tell us about yourself, your interests and favorite genres",
    about_me_placeholder: "Hi everyone! I love sci-fi and indie music...",
    nickname_label: "Nickname",
    nickname_desc: "Your display name on the platform",
    nickname_ph: "Your nickname",
    saves_auto: "Saved automatically",
    avatar_style: "Avatar Style (DiceBear)",
    share_profile: "Share Profile",
    copy_link: "Copy link to my page",
    link_copied: "Link copied!",
    copy_manual: "Copy link manually: ",
    followers_label: "followers",
    following_label: "following",
    followers_title: "Followers",
    following_title: "Following",
    empty_list: "The list is empty",
    profile_hidden: "Profile hidden",
    confirm_delete_account: "Are you sure you want to PERMANENTLY delete your account? This action cannot be undone.",
    folder_empty: "This folder is empty.",
    error_save_settings: "Error saving settings.",
    avatar_updated: "Avatar updated successfully!",
    avatar_upload_error: "Upload error. Make sure you've created a public 'avatars' bucket in Supabase Storage.",
    avatar_style_error: "Error selecting style.",
    error_delete_account: "Error: ",
    // Footer
    footer_explore: "Explore",
    footer_account: "Account",
    footer_rights: "All rights reserved.",
    // Notifications
    notifications_title: "Notifications",
    no_notifications: "You have no notifications yet.",
    user_unknown: "User",
    notif_like: " liked your review! ❤️",
    notif_follow: " followed you!",
    // Dashboard new strings
    dash_content_by_cat: "Content by Categories",
    dash_cat_filter: "Filter by Category",
    dash_stats_for: "Statistics:",
    dash_records: "records",
    dash_rating_dist: "Rating Distribution",
    dash_items_count: "items",
    dash_cat_movies: "🎬 Movies",
    dash_cat_tv: "📺 TV Series",
    dash_cat_books: "📚 Books",
    dash_cat_music: "🎵 Music"
  },
  kz: {
    // AI
    ai_match: "AI Таңдауы",
    why_love_it: "Неге бұл сізге ұнайды:",
    // Profile
    profile_title: "Жеке Кабинет",
    logout: "Аккаунттан шығу",
    favorite_genres: "Сүйікті жанрлар:",
    library: "Медиатека",
    in_watchlist: "Тізімде",
    ratings_left: "Берілген бағалар",
    tab_watchlist: "Менің тізімім",
    tab_my_ratings: "Менің бағаларым",
    tab_settings: "Баптаулар",
    empty_watchlist: "Сіз әлі ештеңе сақтамадыңыз.",
    empty_ratings: "Алдыңызда бағалайтын тамаша дүниелер күтіп тұр!",
    find_cool_stuff: "Керемет бірдеңе табу",
    account_settings: "Аккаунт Баптаулары",
    light_theme: "Жарық тақырып",
    light_theme_desc: "Интерфейстің жарық безендіруін қосу",
    notifications: "Хабарландырулар",
    notifications_desc: "Жаңа ұсыныстары бар хаттар алу",
    public_profile: "Ашық профиль",
    public_profile_desc: "Менің бағаларымды басқа пайдаланушыларға көрсету",
    danger_zone: "Қауіпті аймақ",
    delete_account: "Аккаунтты өшіру",
    delete_account_desc: "Профильді және барлық сақталған деректерді біржолата өшіру",
    delete_btn: "Өшіру",
    language: "Тіл",
    language_desc: "Интерфейс тілін таңдаңыз",
    loading: "Профиль жүктелуде...",
    // Navbar
    nav_movies: "Фильмдер мен Сериалдар",
    nav_books: "Кітаптар",
    nav_music: "Музыка",
    nav_recommend: "Ұсыныстар",
    nav_profile: "Профиль",
    nav_logout: "Шығу",
    nav_login: "Кіру",
    nav_register: "Тіркелу",
    // Categories
    cat_all: "Барлығы",
    cat_movies: "Фильмдер",
    cat_tv: "Сериалдар",
    cat_books: "Кітаптар",
    cat_music: "Музыка",
    // Home
    search_catalog: "Атау, жанр бойынша іздеу...",
    nothing_found: "Кешіріңіз, ештеңе табылмады",
    all_genres: "Барлығы",
    // Books page
    books_title: "Кітапхана",
    books_subtitle: "Тартымды әлемдерге еніңіз. Барлық уақыттағы ең жақсы кітаптар.",
    search_books: "Атау, жанр бойынша іздеу...",
    no_books_found: "Кешіріңіз, кітаптар табылмады",
    // Music page
    music_title: "Плейлист",
    music_subtitle: "Сүйікті тректеріңіз бен аңыз альбомдар бір жерде.",
    search_music: "Атау, жанр, орындаушы бойынша іздеу...",
    no_music_found: "Кешіріңіз, тректер табылмады",
    // Recommendations page
    rec_title: "Ұсыныстар",
    rec_subtitle: "Сіздің талғамыңызға негізделген жеке ұсыныстар.",
    no_recs: "Әзірге ұсыныстар жоқ. Ұсыныстар алу үшін мазмұнды бағалаңыз!",
    rec_ai_analyzing: "AI сіздің талғамыңызды талдауда...",
    rec_ai_fallback: "AI уақытша қолжетімсіз — жанр бойынша ұсыныстар көрсетілді.",
    // ItemDetail page
    back_to_list: "Тізімге оралу",
    no_description: "Сипаттама әзірге жоқ. Біз оны жақында қосамыз!",
    listen_preview: "Үзіндіні тыңдау (30 сек):",
    watch_trailer: "Трейлерді көру:",
    add_watchlist: "Тізімге қосу",
    remove_watchlist: "Тізімнен өшіру",
    item_not_found: "Объект табылмады",
    load_error: "Ақпаратты жүктеу мүмкін болмады. Объект табылмаған болуы мүмкін.",
    back_to_home: "Басты бетке оралу",
    user_reviews: "Пайдаланушылар пікірлері",
    no_reviews: "Әзірге пікір жоқ. Пікіріңізді бөлісіңіз!",
    reply: "Жауап беру",
    write_reply: "Жауап жазыңыз...",
    send: "Жіберу",
    replies_count: "жауаптар",
    show_replies: "Жауаптар",
    hide_replies: "Жасыру",
    delete: "Жою",
    confirm_delete_review: "Бұл пікірді жойғыңыз келетініне сенімдісіз бе?",
    watchlist_login_alert: "Тізімге қосу үшін аккаунтқа кіруіңіз керек!",
    watchlist_error: "Тізімді жаңарту мүмкін болмады.",
    // Rating
    your_rating: "Сіздің бағаңыз және пікіріңіз:",
    review_placeholder: "Әсерлеріңізді жазыңыз...",
    saving: "Сақтау...",
    save_review: "Пікірді сақтау",
    review_saved: "Пікіріңіз сақталды!",
    review_error: "Сақтау кезінде қате.",
    login_to_rate: "Пікір қалдыру үшін аккаунтқа кіруіңіз керек!",
    // HeroSlider
    more_info: "Толығырақ",
    // Login
    login_title: "Қайта келуіңізбен!",
    email_placeholder: "Сіздің Email",
    password_placeholder: "Сіздің Құпия сөз",
    login_btn: "Кіру",
    loading_btn: "Жүктелуде...",
    no_account: "Аккаунтыңыз жоқ па?",
    register_link: "Тіркелу",
    login_error: "Кіру қатесі: ",
    forgot_password: "Құпия сөзді ұмыттыңыз ба?",
    // Forgot Password page
    forgot_title: "Құпия сөзді қалпына келтіру",
    forgot_subtitle: "Email енгізіңіз — біз сізге сілтеме жібереміз.",
    forgot_btn: "Сілтеме жіберу",
    forgot_sent: "Хат жіберілді!",
    forgot_sent_desc: "Поштаңызды тексеріп, құпия сөзді қалпына келтіру сілтемесін басыңыз.",
    forgot_error: "Қате: ",
    back_to_login: "Кіруге оралу",
    // Reset Password page
    reset_title: "Жаңа құпия сөз",
    reset_subtitle: "Аккаунтыңыз үшін сенімді жаңа құпия сөз ойлап табыңыз.",
    reset_new_password: "Жаңа құпия сөз",
    reset_confirm_password: "Құпия сөзді растаңыз",
    reset_btn: "Құпия сөзді сақтау",
    reset_success: "Құпия сөз сәтті өзгертілді!",
    reset_redirect: "Кіру бетіне бағытталуда...",
    reset_password_short: "Құпия сөз кемінде 6 таңбадан тұруы керек.",
    reset_password_mismatch: "Құпия сөздер сәйкес келмейді.",
    reset_error: "Қате: ",
    reset_verifying: "Сілтемені тексеруде...",
    // Register
    register_title: "Аккаунт ашу",
    nickname_placeholder: "Сіздің Лақап атыңыз",
    password_hint: "Құпия сөз ойлап табыңыз (кемінде 8 таңба)",
    pwd_min_8: "Құпия сөз кемінде 8 таңбадан тұруы керек.",
    pwd_latin_only: "Құпия сөз тек ағылшын әріптерін, сандар мен арнайы таңбаларды қамтуы керек.",
    pwd_very_weak: "Өте әлсіз",
    pwd_weak: "Әлсіз",
    pwd_fair: "Орташа",
    pwd_strong: "Күшті",
    pwd_very_strong: "Өте күшті",
    register_btn: "Тіркелу",
    has_account: "Аккаунтыңыз бар ма?",
    login_link: "Кіру",
    check_email: "Аккаунтты растау үшін поштаңызды тексеріңіз!",
    // Admin
    nav_admin: "Админ",
    admin_panel: "Админ-панель",
    admin_dashboard: "Дашборд",
    admin_dashboard_desc: "Платформаның жалпы статистикасы",
    admin_users: "Пайдаланушылар",
    admin_users_desc: "Пайдаланушы аккаунттарын басқару",
    admin_content: "Контент",
    admin_content_desc: "Фильмдерді, сериалдарды, кітаптарды және музыканы басқару",
    admin_reviews: "Пікірлер",
    admin_reviews_desc: "Пікірлер мен рейтингтерді модерациялау",
    admin_access_denied: "Кіруге тыйым салынған",
    admin_access_denied_desc: "Сізде бұл бетке кіру үшін әкімші құқықтары жоқ.",
    admin_stat_users: "Пайдаланушылар",
    admin_stat_content: "Контент бірліктері",
    admin_stat_reviews: "Пікірлер",
    admin_stat_avg_rating: "Орташа рейтинг",
    admin_top_rated: "Рейтинг бойынша үздік",
    admin_top_watchlisted: "Сақтаулар бойынша үздік",
    admin_reviews_count: "пікір",
    admin_saves: "сақтау",
    admin_no_data: "Деректер жоқ",
    admin_search_users: "Email бойынша іздеу...",
    admin_users_total: "пайдаланушы",
    admin_col_user: "Пайдаланушы",
    admin_col_reviews: "Пікірлер",
    admin_col_status: "Күй",
    admin_col_role: "Рөл",
    admin_col_registered: "Тіркелу",
    admin_col_actions: "Әрекеттер",
    admin_col_title: "Атауы",
    admin_col_category: "Санат",
    admin_col_genre: "Жанр",
    admin_col_content: "Контент",
    admin_col_rating: "Рейтинг",
    admin_col_review: "Пікір",
    admin_col_date: "Күні",
    admin_banned: "Бұғатталған",
    admin_active: "Белсенді",
    admin_role_admin: "Әкімші",
    admin_ban: "Бұғаттау",
    admin_unban: "Бұғаттан шығару",
    admin_make_admin: "Әкімші ету",
    admin_remove_admin: "Әкімшіні алып тастау",
    admin_make_manager: "Менеджер ету",
    admin_remove_manager: "Менеджерді алып тастау",
    admin_role_manager: "Менеджер",
    admin_confirm_make_manager: "Менеджер ету керек пе?",
    admin_confirm_remove_manager: "Менеджер рөлін алып тастау керек пе?",
    manager_panel: "Менеджер-панелі",
    nav_manager: "Менеджер",
    admin_no_users: "Пайдаланушылар табылмады",
    admin_confirm_title: "Растау",
    admin_confirm_ban: "Пайдаланушыны бұғаттау керек пе?",
    admin_confirm_unban: "Бұғаттан шығару керек пе?",
    admin_confirm_make_admin: "Әкімші ету керек пе?",
    admin_confirm_remove_admin: "Әкімші рөлін алып тастау керек пе?",
    admin_confirm_delete_user: "Пайдаланушыны жою керек пе?",
    admin_confirm_delete_item: "Бұл контентті жою керек пе?",
    admin_confirm_delete_review: "Бұл пікірді жою керек пе?",
    admin_cancel: "Бас тарту",
    admin_confirm: "Растау",
    admin_search_content: "Контентті іздеу...",
    admin_add_item: "Қосу",
    admin_edit: "Өзгерту",
    admin_edit_item: "Контентті өзгерту",
    admin_edit_item_desc: "Каталог элементін жаңарту",
    admin_add_item_desc: "Каталогқа жаңа элемент қосу",
    admin_no_content: "Контент табылмады",
    admin_fill_required: "Міндетті өрістерді толтырыңыз",
    admin_save_error: "Сақтау қатесі",
    admin_delete_error: "Жою қатесі",
    admin_save: "Сақтау",
    admin_desc_ru: "Сипаттама (RU)",
    admin_desc_en: "Сипаттама (EN)",
    admin_desc_kz: "Сипаттама (KZ)",
    admin_image_url: "Постер URL",
    admin_trailer_url: "Трейлер URL",
    admin_preview_url: "Аудио URL",
    admin_artist: "Орындаушы",
    admin_search_reviews: "Пікірлерді іздеу...",
    admin_reviews_total: "пікір",
    admin_no_reviews: "Пікірлер табылмады",
    viewing_now: "қазір қарауда",
    director: "Режиссер",
    cast: "Рөлдерде",
    // Filter & Profile extras
    filter_btn: "Сүзгі",
    adv_filter_title: "Кеңейтілген сүзгі",
    adv_sort_by: "Сұрыптау",
    adv_category: "Санат",
    adv_genres: "Жанрлар",
    adv_selected: "таңдалды",
    adv_found: "Табылды",
    adv_apply: "Қолдану",
    adv_filter_reset: "Тазарту",
    sort_default: "Әдепкі",
    sort_title_asc: "Атау А→Я",
    sort_title_desc: "Атау Я→А",
    sort_rating_desc: "Рейтинг ↓",
    sort_rating_asc: "Рейтинг ↑",
    sort_year_desc: "Жаңалар",
    sort_year_asc: "Ескілер",
    tab_feed: "Белсенділік лентасы",
    folder_all: "Барлығы",
    folder_unsorted: "Қалтасыз",
    folder_planned: "Жоспарда",
    folder_watching: "Қарауда",
    folder_watched: "Қаралды",
    folder_dropped: "Тасталды",
    folder_assign: "Қалтаға...",
    remove_folder: "Қалтадан алып тастау",
    about_me: "Өзім туралы",
    about_me_desc: "Өзіңіз, қызығушылықтарыңыз және сүйікті жанрларыңыз туралы айтыңыз",
    about_me_placeholder: "Бәріне сәлем! Ғылыми фантастика мен инди-музыканы жақсы көремін...",
    nickname_label: "Лақап ат",
    nickname_desc: "Платформадағы көрсетілетін атыңыз",
    nickname_ph: "Сіздің лақап атыңыз",
    saves_auto: "Автоматты түрде сақталады",
    avatar_style: "Аватар стилі (DiceBear)",
    share_profile: "Профильді бөлісу",
    copy_link: "Менің бетіме сілтемені көшіру",
    link_copied: "Сілтеме көшірілді!",
    copy_manual: "Сілтемені қолмен көшіріңіз: ",
    followers_label: "жазылушылар",
    following_label: "жазылымдар",
    followers_title: "Жазылушылар",
    following_title: "Жазылымдар",
    empty_list: "Тізім бос",
    profile_hidden: "Профиль жасырын",
    confirm_delete_account: "Аккаунтыңызды МӘҢГІЛІККЕ жойғыңыз келетініне сенімдісіз бе? Бұл әрекетті кері қайтару мүмкін емес.",
    folder_empty: "Бұл қалта бос.",
    error_save_settings: "Баптауларды сақтау қатесі.",
    avatar_updated: "Аватар сәтті жаңартылды!",
    avatar_upload_error: "Жүктеу қатесі. Supabase Storage-да 'avatars' бакетін жасағаныңызды тексеріңіз.",
    avatar_style_error: "Стильді таңдау қатесі.",
    error_delete_account: "Қате: ",
    // Footer
    footer_explore: "Зерттеу",
    footer_account: "Аккаунт",
    footer_rights: "Барлық құқықтар қорғалған.",
    // Notifications
    notifications_title: "Хабарландырулар",
    no_notifications: "Әзірге хабарландырулар жоқ.",
    user_unknown: "Пайдаланушы",
    notif_like: " сіздің пікіріңізді бағалады! ❤️",
    notif_follow: " сізге жазылды!",
    // Dashboard new strings
    dash_content_by_cat: "Санат бойынша контент",
    dash_cat_filter: "Санат бойынша сүзгі",
    dash_stats_for: "Статистика:",
    dash_records: "жазба",
    dash_rating_dist: "Бағалар үлестірімі",
    dash_items_count: "дана",
    dash_cat_movies: "🎬 Фильмдер",
    dash_cat_tv: "📺 Сериалдар",
    dash_cat_books: "📚 Кітаптар",
    dash_cat_music: "🎵 Музыка"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('app-lang') || 'ru');

  useEffect(() => {
    localStorage.setItem('app-lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['ru']?.[key] || key;
  };

  const translateCategory = (cat) => {
    if (!cat) return cat;
    const lowerCat = cat.toLowerCase();
    if (lowerCat.includes("фильм") || lowerCat.includes("movi")) return t('cat_movies');
    if (lowerCat.includes("сериал") || lowerCat.includes("tv")) return t('cat_tv');
    if (lowerCat.includes("книг") || lowerCat.includes("book")) return t('cat_books');
    if (lowerCat.includes("музык") || lowerCat.includes("music")) return t('cat_music');
    return cat;
  };

  const genreTranslations = {
    'action': { ru: 'Боевик', en: 'Action', kz: 'Атыс-шабыс' },
    'боевик': { ru: 'Боевик', en: 'Action', kz: 'Атыс-шабыс' },
    'adventure': { ru: 'Приключения', en: 'Adventure', kz: 'Шытырман оқиғалы' },
    'приключения': { ru: 'Приключения', en: 'Adventure', kz: 'Шытырман оқиғалы' },
    'animation': { ru: 'Анимация', en: 'Animation', kz: 'Анимация' },
    'анимация': { ru: 'Анимация', en: 'Animation', kz: 'Анимация' },
    'biography': { ru: 'Биография', en: 'Biography', kz: 'Өмірбаян' },
    'биография': { ru: 'Биография', en: 'Biography', kz: 'Өмірбаян' },
    'character study': { ru: 'Исследование характера', en: 'Character Study', kz: 'Мінезді зерттеу' },
    'исследование характера': { ru: 'Исследование характера', en: 'Character Study', kz: 'Мінезді зерттеу' },
    'comedy': { ru: 'Комедия', en: 'Comedy', kz: 'Комедия' },
    'комедия': { ru: 'Комедия', en: 'Comedy', kz: 'Комедия' },
    'documentary': { ru: 'Документальный', en: 'Documentary', kz: 'Деректі' },
    'документальный': { ru: 'Документальный', en: 'Documentary', kz: 'Деректі' },
    'drama': { ru: 'Драма', en: 'Drama', kz: 'Драма' },
    'драма': { ru: 'Драма', en: 'Drama', kz: 'Драма' },
    'epic': { ru: 'Эпос', en: 'Epic', kz: 'Эпос' },
    'эпический': { ru: 'Эпос', en: 'Epic', kz: 'Эпос' },
    'family': { ru: 'Семейный', en: 'Family', kz: 'Отбасылық' },
    'семейный': { ru: 'Семейный', en: 'Family', kz: 'Отбасылық' },
    'fantasy': { ru: 'Фэнтези', en: 'Fantasy', kz: 'Фэнтези' },
    'фэнтези': { ru: 'Фэнтези', en: 'Fantasy', kz: 'Фэнтези' },
    'history': { ru: 'История', en: 'History', kz: 'Тарих' },
    'история': { ru: 'История', en: 'History', kz: 'Тарих' },
    'horror': { ru: 'Ужасы', en: 'Horror', kz: 'Қорқынышты' },
    'ужасы': { ru: 'Ужасы', en: 'Horror', kz: 'Қорқынышты' },
    'kids': { ru: 'Детский', en: 'Kids', kz: 'Балаларға арналған' },
    'детский': { ru: 'Детский', en: 'Kids', kz: 'Балаларға арналған' },
    'music documentaries': { ru: 'Музыкальные док.', en: 'Music Docs', kz: 'Музыкалық деректі' },
    'музыкальные документальные': { ru: 'Музыкальные док.', en: 'Music Docs', kz: 'Музыкалық деректі' },
    'nonfiction': { ru: 'Нон-фикшн', en: 'Nonfiction', kz: 'Нон-фикшн' },
    'документальная литература/нон-фикшн': { ru: 'Нон-фикшн', en: 'Nonfiction', kz: 'Нон-фикшн' },
    'reality': { ru: 'Реалити-шоу', en: 'Reality', kz: 'Реалити-шоу' },
    'реалити': { ru: 'Реалити-шоу', en: 'Reality', kz: 'Реалити-шоу' },
    'romance': { ru: 'Мелодрама', en: 'Romance', kz: 'Мелодрама' },
    'романтика': { ru: 'Мелодрама', en: 'Romance', kz: 'Мелодрама' },
    'sci-fi': { ru: 'Фантастика', en: 'Sci-Fi', kz: 'Фантастика' },
    'научная фантастика': { ru: 'Фантастика', en: 'Sci-Fi', kz: 'Фантастика' },
    'thriller': { ru: 'Триллер', en: 'Thriller', kz: 'Триллер' },
    'триллер': { ru: 'Триллер', en: 'Thriller', kz: 'Триллер' },
    'western': { ru: 'Вестерн', en: 'Western', kz: 'Вестерн' },
    'вестерн': { ru: 'Вестерн', en: 'Western', kz: 'Вестерн' },

    // Music and Books
    'alternative': { ru: 'Альтернатива', en: 'Alternative', kz: 'Альтернатива' },
    'blues': { ru: 'Блюз', en: 'Blues', kz: 'Блюз' },
    'christian': { ru: 'Христианская', en: 'Christian', kz: 'Христиан діни' },
    'country': { ru: 'Кантри', en: 'Country', kz: 'Кантри' },
    'dance': { ru: 'Танцевальная', en: 'Dance', kz: 'Би' },
    'electronic': { ru: 'Электронная', en: 'Electronic', kz: 'Электронды' },
    'folk': { ru: 'Фолк', en: 'Folk', kz: 'Фолк' },
    'hard rock': { ru: 'Хард-рок', en: 'Hard Rock', kz: 'Хард-рок' },
    'k-pop': { ru: 'K-Pop', en: 'K-Pop', kz: 'K-Pop' },
    'metal': { ru: 'Метал', en: 'Metal', kz: 'Метал' },
    'pop': { ru: 'Поп', en: 'Pop', kz: 'Поп' },
    'r&b': { ru: 'R&B', en: 'R&B', kz: 'R&B' },
    'rock': { ru: 'Рок', en: 'Rock', kz: 'Рок' },
    'soul': { ru: 'Соул', en: 'Soul', kz: 'Соул' },
    'science fiction': { ru: 'Научная фантастика', en: 'Science Fiction', kz: 'Ғылыми фантастика' },
    'mystery': { ru: 'Детектив', en: 'Mystery', kz: 'Детектив' },
    'novel': { ru: 'Роман', en: 'Novel', kz: 'Роман' },
    'non-fiction': { ru: 'Нон-фикшн', en: 'Non-fiction', kz: 'Нон-фикшн' },

    // Additions for missing genres from Admin and AI fill
    'crime': { ru: 'Криминал', en: 'Crime', kz: 'Криминал' },
    'musical': { ru: 'Мюзикл', en: 'Musical', kz: 'Мюзикл' },
    'war': { ru: 'Военный', en: 'War', kz: 'Әскери' },
    'classic': { ru: 'Классика', en: 'Classic', kz: 'Классика' },
    'poetry': { ru: 'Поэзия', en: 'Poetry', kz: 'Поэзия' },
    'children': { ru: 'Детская литература', en: 'Children', kz: 'Балалар әдебиеті' },
    'hip-hop': { ru: 'Хип-хоп', en: 'Hip-Hop', kz: 'Хип-хоп' },
    'jazz': { ru: 'Джаз', en: 'Jazz', kz: 'Джаз' },
    'classical': { ru: 'Классическая', en: 'Classical', kz: 'Классикалық' },
    'indie': { ru: 'Инди', en: 'Indie', kz: 'Инди' },
    'reggae': { ru: 'Регги', en: 'Reggae', kz: 'Регги' },
    'historical fiction': { ru: 'Исторический роман', en: 'Historical Fiction', kz: 'Тарихи роман' },
    'biographical fiction': { ru: 'Биографический роман', en: 'Biographical Fiction', kz: 'Өмірбаяндық роман' },
    'education': { ru: 'Образование', en: 'Education', kz: 'Білім' },
    'finance': { ru: 'Финансы', en: 'Finance', kz: 'Қаржы' },
    'self-help': { ru: 'Саморазвитие', en: 'Self-Help', kz: 'Өзін-өзі дамыту' },

    // Additional music and miscellaneous genres
    'house': { ru: 'Хаус', en: 'House', kz: 'Хаус' },
    'musicals': { ru: 'Мюзиклы', en: 'Musicals', kz: 'Мюзиклдер' },
    'singer': { ru: 'Исполнитель', en: 'Singer', kz: 'Орындаушы' },
    'songwriter': { ru: 'Автор песен', en: 'Songwriter', kz: 'Ән авторы' },
    'singer/songwriter': { ru: 'Автор-исполнитель', en: 'Singer/Songwriter', kz: 'Автор-орындаушы' },
    'vocal': { ru: 'Вокал', en: 'Vocal', kz: 'Вокал' },

    // iTunes Music — common untranslated genres
    'hip-hop/rap': { ru: 'Хип-хоп/Рэп', en: 'Hip-Hop/Rap', kz: 'Хип-хоп/Рэп' },
    'rap': { ru: 'Рэп', en: 'Rap', kz: 'Рэп' },
    'r&b/soul': { ru: 'R&B/Соул', en: 'R&B/Soul', kz: 'R&B/Соул' },
    'pop/rock': { ru: 'Поп/Рок', en: 'Pop/Rock', kz: 'Поп/Рок' },
    'latin': { ru: 'Латинская', en: 'Latin', kz: 'Латын' },
    'latin pop': { ru: 'Латинский поп', en: 'Latin Pop', kz: 'Латын попы' },
    'world': { ru: 'Мировая', en: 'World', kz: 'Әлемдік' },
    'worldwide': { ru: 'Мировая', en: 'Worldwide', kz: 'Әлемдік' },
    'spoken word': { ru: 'Разговорный жанр', en: 'Spoken Word', kz: 'Сөз өнері' },
    'soundtrack': { ru: 'Саундтрек', en: 'Soundtrack', kz: 'Саундтрек' },
    'soundtracks': { ru: 'Саундтреки', en: 'Soundtracks', kz: 'Саундтректер' },
    'new age': { ru: 'Нью-эйдж', en: 'New Age', kz: 'Жаңа дәуір' },
    'ambient': { ru: 'Эмбиент', en: 'Ambient', kz: 'Эмбиент' },
    'trap': { ru: 'Трэп', en: 'Trap', kz: 'Трэп' },
    'afrobeats': { ru: 'Афробит', en: 'Afrobeats', kz: 'Афробит' },
    'afro': { ru: 'Афро', en: 'Afro', kz: 'Афро' },
    'dancehall': { ru: 'Дэнсхолл', en: 'Dancehall', kz: 'Дэнсхолл' },
    'gospel': { ru: 'Госпел', en: 'Gospel', kz: 'Госпел' },
    'funk': { ru: 'Фанк', en: 'Funk', kz: 'Фанк' },
    'punk': { ru: 'Панк', en: 'Punk', kz: 'Панк' },
    'punk rock': { ru: 'Панк-рок', en: 'Punk Rock', kz: 'Панк-рок' },
    'grunge': { ru: 'Гранж', en: 'Grunge', kz: 'Гранж' },
    'rnb': { ru: 'R&B', en: 'R&B', kz: 'R&B' },
    'disco': { ru: 'Диско', en: 'Disco', kz: 'Диско' },
    'opera': { ru: 'Опера', en: 'Opera', kz: 'Опера' },
    'children\'s music': { ru: 'Детская музыка', en: "Children's Music", kz: 'Балалар музыкасы' },
    'holiday': { ru: 'Праздничная', en: 'Holiday', kz: 'Мереке' },
    'inspirational': { ru: 'Вдохновляющая', en: 'Inspirational', kz: 'Шабыттандырушы' },
    'easy listening': { ru: 'Лёгкое слушание', en: 'Easy Listening', kz: 'Жеңіл тыңдау' },
    'tejano': { ru: 'Техано', en: 'Tejano', kz: 'Техано' },
    'regional mexican': { ru: 'Мексиканский', en: 'Regional Mexican', kz: 'Мексикалық' },
    'banda': { ru: 'Банда', en: 'Banda', kz: 'Банда' },

    // iTunes Movies — common untranslated genres
    'action & adventure': { ru: 'Боевик и приключения', en: 'Action & Adventure', kz: 'Атыс-шабыс және шытырман' },
    'kids & family': { ru: 'Детское и семейное', en: 'Kids & Family', kz: 'Балалар және отбасы' },
    'science fiction & fantasy': { ru: 'Фантастика и фэнтези', en: 'Science Fiction & Fantasy', kz: 'Фантастика және фэнтези' },
    'special interest': { ru: 'Особый интерес', en: 'Special Interest', kz: 'Арнайы тақырып' },
    'sports & outdoors': { ru: 'Спорт', en: 'Sports & Outdoors', kz: 'Спорт' },
    'concert film': { ru: 'Концертный фильм', en: 'Concert Film', kz: 'Концерт фильмі' },
    'short film': { ru: 'Короткометражный', en: 'Short Film', kz: 'Қысқаметражды' },
    'foreign language': { ru: 'Зарубежный', en: 'Foreign Language', kz: 'Шетелдік' },
    'anime': { ru: 'Аниме', en: 'Anime', kz: 'Аниме' },
    'arts & entertainment': { ru: 'Искусство', en: 'Arts & Entertainment', kz: 'Өнер' },
    'fitness & workout': { ru: 'Фитнес', en: 'Fitness & Workout', kz: 'Фитнес' },
    'gay & lesbian': { ru: 'ЛГБТК+', en: 'Gay & Lesbian', kz: 'ЛГБТК+' },

    // TV genres
    'talk show': { ru: 'Ток-шоу', en: 'Talk Show', kz: 'Ток-шоу' },
    'game show': { ru: 'Игровое шоу', en: 'Game Show', kz: 'Ойын-сауық шоу' },
    'news': { ru: 'Новости', en: 'News', kz: 'Жаңалықтар' },
    'mini-series': { ru: 'Мини-сериал', en: 'Mini-Series', kz: 'Мини-сериал' },
    'miniseries': { ru: 'Мини-сериал', en: 'Miniseries', kz: 'Мини-сериал' },

    // Missing from screenshot
    'erotic': { ru: 'Эротика', en: 'Erotic', kz: 'Эротика' },
    'эротика': { ru: 'Эротика', en: 'Erotic', kz: 'Эротика' },
    'historical': { ru: 'Исторический', en: 'Historical', kz: 'Тарихи' },
    'исторический': { ru: 'Исторический', en: 'Historical', kz: 'Тарихи' },
    'reality tv': { ru: 'Реалити-шоу', en: 'Reality TV', kz: 'Реалити-шоу' },
    'teen drama': { ru: 'Подростковая драма', en: 'Teen Drama', kz: 'Жасөспірімдер драмасы' },
    'teen': { ru: 'Подростковый', en: 'Teen', kz: 'Жасөспірімдер' },
    'supernatural': { ru: 'Сверхъестественное', en: 'Supernatural', kz: 'Паранормальды' },
    'mystery & thriller': { ru: 'Детектив и триллер', en: 'Mystery & Thriller', kz: 'Детектив және триллер' },
    'crime drama': { ru: 'Криминальная драма', en: 'Crime Drama', kz: 'Криминалдық драма' },
    'period drama': { ru: 'Историческая драма', en: 'Period Drama', kz: 'Тарихи драма' },
    'medical': { ru: 'Медицинский', en: 'Medical', kz: 'Медициналық' },
    'legal': { ru: 'Юридический', en: 'Legal', kz: 'Заңдық' },
    'political': { ru: 'Политический', en: 'Political', kz: 'Саяси' },
    'spy': { ru: 'Шпионский', en: 'Spy', kz: 'Тыңшы' },
    'cyberpunk': { ru: 'Киберпанк', en: 'Cyberpunk', kz: 'Киберпанк' },
    'post-apocalyptic': { ru: 'Постапокалипсис', en: 'Post-Apocalyptic', kz: 'Постапокалипсис' },
    'dystopian': { ru: 'Антиутопия', en: 'Dystopian', kz: 'Антиутопия' },
    'sitcom': { ru: 'Ситком', en: 'Sitcom', kz: 'Ситком' },

    // Missing music genres from screenshot
    'indie rock': { ru: 'Инди-рок', en: 'Indie Rock', kz: 'Инди-рок' },
    'soft rock': { ru: 'Мягкий рок', en: 'Soft Rock', kz: 'Жұмсақ рок' },
    'indie pop': { ru: 'Инди-поп', en: 'Indie Pop', kz: 'Инди-поп' },
    'alt-pop': { ru: 'Альт-поп', en: 'Alt-Pop', kz: 'Альт-поп' },
    'alt rock': { ru: 'Альт-рок', en: 'Alt Rock', kz: 'Альт-рок' },
    'alternative rock': { ru: 'Альтернативный рок', en: 'Alternative Rock', kz: 'Балама рок' },
    'pop rap': { ru: 'Поп-рэп', en: 'Pop Rap', kz: 'Поп-рэп' },
    'dance pop': { ru: 'Дэнс-поп', en: 'Dance Pop', kz: 'Дэнс-поп' },
    'electropop': { ru: 'Электропоп', en: 'Electropop', kz: 'Электропоп' },
    'synth-pop': { ru: 'Синти-поп', en: 'Synth-Pop', kz: 'Синти-поп' },
    'bedroom pop': { ru: 'Бедрум-поп', en: 'Bedroom Pop', kz: 'Бедрум-поп' },
    'j-pop': { ru: 'J-Pop', en: 'J-Pop', kz: 'J-Pop' },
    'j-rock': { ru: 'J-Rock', en: 'J-Rock', kz: 'J-Rock' }
  };

  const translateGenre = (genre) => {
    if (!genre) return genre;
    const lowerGenre = genre.toLowerCase().trim();
    if (genreTranslations[lowerGenre] && genreTranslations[lowerGenre][language]) {
      return genreTranslations[lowerGenre][language];
    }
    return genre;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateCategory, translateGenre }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
